# The services part
services:
  # mariadb
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

  # nginx
  nginx:
    image: nginx:user
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

  # wordpress
  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always

# The volumes part
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ${DB_DATA}
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ${WP_DATA}
      o: bind
      type: none

# The networks part
networks:
  inception:
    name: inception
